### PR TITLE
list bins management command

### PR DESCRIPTION
**Pull request by joefutrelle**
This new command provides the ability to produce lists of bins on the backend based on filter parameters, and optionally to take action to move bins between datasets.

### CODE REVIEW

**Comment by mike-kaimika** [comment]
@joefutrelle it looks like what it say sit does from the help text, but I'd consider:

1. Renaming it to something other than "listbins", because it has the potential to be destructive with the `--remove-dataset` argument. E.g., "managebins"
2. Split the add and remove flags to a separate command

I could be persuaded against it, but with something named "list" I think of it as not destructive and that the `--remove-dataset` flag wouldn't actually physically delete something. You could interpret that as "find me these matching records, but remove this dataset from the list of returned results"

**Comment by joefutrelle** [comment]
This is on track to become a kind of "swiss army knife" for dealing with filtered lists of bins, and I think that approach might be easier to maintain than a set of commands all of which take all the filtering params. So I'm inclined to go for just renaming it to something that reflects this multi-purpose usage, like `bintool` (since it's used for things other than "managing" bins). If we go with 2 instead, we just need a common codebase for the filtering args and the impl of filtering so we're not repeating ourselves.

**Comment by joefutrelle** [comment]
> If listbins were used to remove a time series association but bin files remain in the directory associated with the removed time series, association will be reestablished on next accession.

True, but why would an IFCB data manager put themselves in this situation?

**Comment by mike-kaimika** [comment]
@joefutrelle I'm good with calling it `bintools`. Agreed on needing to pull out a common library/class if there were separate commands that all needed to do filtering

To cover the other scenarios mentioned, you could add additional flags, like `is_deleted` to indicate a soft delete and prevent accession re-adding it on the next sync. And then the opposite `missing_files` or something to that effect to indicate there's physical files missing.

But those would likely be out of scope for this particular tool/command

**Comment by joefutrelle** [comment]
OK, awaiting additional feedback / discussion from @mbrosnahan (or others) before proceeding further.

**Comment by mbrosnahan** [comment]
I tinkered a bit with habon-ifcb instance to evaluate how listbins (now bintool) behaves and potential for conflict with regular accession behavior.

Experiment 1:
Used listbins to assign a time series [NEW] to bins present/associated with another time series [OLD]. Bin data is present in [OLD] data directory but not in [NEW].
Result: Records of bins are visible in [NEW] time series page but image data is not (no collage). Records and images are both visible/accessible via OLD webpage..

Experiment 2:
Used listins to remove [OLD] time series from bins assigned to [NEW] in experiment 1.
Result: Bins no longer visible or accessible in dataset OLD. This is true both via Web interface/timeline and when using listbins function to filter/query dataset OLD.

Experiment 3:
Used Dataset Management (Web UI) tool to repeat accession of [OLD]. 
Results: NEW bins added back to OLD. This is contrary to @joefutrelle here.

Experiment 4:
Used listbins to repeat remove-dataset of bins from OLD then confirmed not present via both listbins query and refresh of webpage. Next, used Web UI accession tool again but checked 'Newest data only'.
Result: NEW bins not added back to OLD. This is in agreement with @joefutrelle note.

Experiment 5:
Repeated Experiment 4 but used 'manage.py syncdataset --newest OLD'. Same result as Experiment 4. Bins not added back to time series.

Experiment 6:
Repeated Experiment 3 but used 'manage.py sync dataset OLD'.  Same result as Experiment 3. Bins added back (listbins action overwritten by syncdataset tool).

**Comment by joefutrelle** [comment]
Apologies for the misstatement above. Here's the actual logic that will re-add a bin when it already exists. Everything is working as intended; @mbrosnahan you're bringing up new use cases that aren't covered in the current design which is why you're seeing behavior you don't want.

https://github.com/WHOIGit/ifcbdb/blob/f0bdcd5a5364c2682ec1eea4a8dcc7181ad32da3/ifcbdb/dashboard/accession.py#L143-L151

The current design is based on the idea that a dataset is the mechanism for associating directories with bins, not the bin object. If you want arbitrary combinations of bins, datasets, and directories, there would need to be a fundamental change to how we model and implement the location of the data for a bin, as well as the management tools around them.

I can see some ways to handle some of these scenarios without such a fundamental redesign. For instance you can have more than one dataset point to the same directory and then you can add/remove the bin from either or both datasets without breaking the link to the data or requiring syncing more than once.

**Comment by joefutrelle** [comment]
I'm inclined to merge this, since it's working as intended, and work on new features and capabilities in another PR.

**Comment by mbrosnahan** [comment]
Thanks, Joe and Mike, for discussion here. Wonderful that listbins add/remove dataset functions are available now!

**Pull request merged**
