### PR TITLE
Faster mosaic implementation using Numba

### PR DESCRIPTION
**Pull request by joefutrelle**

### CODE REVIEW

**Comment by joefutrelle** [comment]
@mike-kaimika note the latest commit on this that you should pull down, should eliminate slow mosaic generation on first hit

**Comment by mike-kaimika** [comment]
@joefutrelle I pulled this down and it does generate the mosaic. Its hard to tell because I only have such a small sample dataset, but it did seem a bit faster. However, that's going from like a second to render a page to less than a second, so its hard to actually tell. It didn't make anything slower, and I didn't notice any of the slowdown you mentioned that could happen on the first load

I did notice some issues with the mosaic - I'm wondering if maybe the code to pull and show the mosaic isn't matching the selection piece anymore? Clicking on the mosaic isn't producing the correct image on the side/top. 

For example. click in these two locations pops up two different images (both incorrect):
image

The left circle brings up this one:
image

And the right circle brings up:
image

And neither match what was clicked on in the mosaic

**Comment by joefutrelle** [comment]
Good catch. Confirmed that this is broken

**Comment by mike-kaimika** [comment]
@joefutrelle Yes, looking much better now. Everything I clicked on came up accurately and all of the mosaic rendered quickly. This one is good to go as far as I can tell

**Pull request merged**
